### PR TITLE
Try to unify methods for accessing resources across DBAdapter

### PR DESCRIPTION
**Pull request by ghost**
I tried to put some examples in Tests.java... This probably needs some work but at least it all works right now.

To add a new semester, all we can just plop it into the `raw/` directory (you can even test it - copy one of the current semesters into a new file and run Tests to see the new semester show up). 

@cloud0x9 I refactored a bunch of your code (partly just to use enums and try out Java's functional programming, but partly to add some abstractions), let me know if you want to make any changes. With the current  code, to add new regex or edit formatting functions you just have to edit the switch statement in applyRegex (and maybe add a value to the outputType enum).

@jamisonv93 I haven't updated the GUI to use the new methods, but if you test the `.jar` from the `dist` directory you can see that the semesters (and the rest of the db) should be available. All of the "getSomething" methods in DBAdaptor along with removeCourse and SaveCourse should work straight from the jar - only regenDB and regenSemesterList need to be run from netbeans.

### CODE REVIEW

**Comment by ghost** [comment]
I was thinking about removing the DB files when I rebase (and adding them to .gitignore), does that seem reasonable?

**Comment by xsfar** [comment]
Looks good, but I couldn't run it though, don't know if its still a work in progress, I got a bunch of Null Pointer Exceptions,  not sure if thats only me, not sure if it should be merged now, or after todays class since one of us is going to present today and I couldn't get it to run, it might be just me I don't know.

**Comment by xsfar** [comment]
> I was thinking about removing the DB files when I rebase (and adding them to .gitignore), does that seem reasonable?

Not sure really, but just a heads up, currently ParseData only works on any spring semester, so regenDB wouldn't work fullly and subsequently all the get methods for fall or summer, since I built the original regex around the spring semester format, so it can not build a full DB for any summer or fall semesters, but its an really easy fix, i'll update the regex later so a full DB can be built for any fall and summer semesters. So if you are going to run any tests before I update it, use any spring semester for the tests.

**Comment by ghost** [comment]
Yeah let's not merge this before class. Can you try running Tests.java twice (it should fail the first time, then work the second time)? I can explain why in class, it's a bug I don't know how to fix yet.

>Not sure really, but just a heads up, currently ParseData only works on any spring semester, so regenDB wouldn't work fullly and subsequently all the get methods for fall or summer, since I built the original regex around the spring semester format, so it can not build a full DB for any summer or fall semesters, but its an really easy fix, i'll update the regex later so a full DB can be built for any fall and summer semesters. So if you are going to run any tests before I update it, use any spring semester for the tests.

Thanks for the heads up. I assume there's just some extra matching to add for the Summer semester? On my laptop your regex does correctly generate the courses and all_info for Summer 2020 (but I don't know if there's stuff missing).

**Pull request closed without merging**
