### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jamisonvalentine** [comment]
Are we going to merge this PR too? Trying to get caught up on my local repo before I start making changes

**Comment by ghost** [comment]
I mean yes, but this is a big PR that technically touches everyone's code so I didn't feel qualified to merge it yet.

**Comment by ghost** [comment]
But yeah it's probably safe to pull from this branch if you want to start working on another feature.

**Comment by jamisonvalentine** [comment]
you mean it's safe to pull from "master" or "reformat"?

**Comment by ghost** [comment]
I meant from "reformat".

**Comment by jamisonvalentine** [comment]
Might need some help w/ the new setup. What changes should we be making in our local repos?

**Comment by ghost** [comment]
This is the quigley-certified repository setup:
- make a new project in netbeans
- delete the default package and class
- navigate to the src/ subdirectory (you can use the regular file manager, then click the url line and type "cmd" and press enter
- `git clone <url> .` (note the trailing dot)

In this case, use the git url of this repository but then `git checkout reformat` to test my patch.

**Comment by jamisonvalentine** [comment]
image
 
Doesn't look right but this is what I end up with

**Comment by jamisonvalentine** [comment]
Tried to follow those steps, but I end up with something really complicated each time

**Comment by ghost** [comment]
Mine looks similar. Which errors are you getting?
Screenshot2020-02-21-113418

What are the outputs of `cd` and `git status`? Are you sure you're in the `reformat` branch?

**Comment by jamisonvalentine** [comment]
Ah, I see now. I didn't know if that was how it was supposed to look. If that's the case, I'm good to go.

**Comment by ghost** [comment]
You're welcome to push more commits to this branch or merge it into your own branch. Alternatively, if you work from master I can rebuild this pull request some other time before Tuesday.
Paging @cloud0x9 and @toldge too, do you guys think this reformat look good?

**Comment by jamisonvalentine** [comment]
Just now seeing this commit. I went ahead and created another pull request for some changes I made in another branch. Can you guys check it out after you review the reformat?

**Comment by xsfar** [comment]
looks good to me, but the parse data class doesn't run anymore, at least for me.

**Comment by ghost** [comment]
@cloud0x9 on this branch or Jamison's? Btw we're in the computer lab if you want to join us

**Comment by xsfar** [comment]
@wrycode this reformat branch, the Boilerplate class looks to have the right file path to the class data but it's not being picked up for some reason, no file found exception.

**Comment by ghost** [comment]
@cloud0x9 I'm not sure what's wrong, I wasn't able to reproduce this. Maybe a Netbeans refresh problem?

**Pull request merged**
