### PR TITLE
Add fall 2020 full course schedule, simplified course list, and admin class GenerateCourseList that was used

### PR DESCRIPTION
**Pull request by jamisonvalentine**

### CODE REVIEW

**Comment by jamisonvalentine** [comment]
The admin package is completely optional but I think it would be nice to have in theory for when we need to make any changes in the database

**Comment by ghost** [comment]
Nice, just saw this. What about an Admin class and we can move DBAdapter.regenDB and regenSemesterList into it  since they're semantically similar?

**Comment by xsfar** [comment]
@jamisonv93 is it okay to remove the admin class from this branch so it can be merged to add the new semester files, merging now would create two admin classes.

**Comment by jamisonvalentine** [comment]
@cloud0x9 cool with me. You might want to check with Nick because I there's an easier way to generate the necessary fall data files using the admin methods. Up to you though....

**Comment by ghost** [comment]
@jamisonv93 are these the original files or the messed up ones: https://github.com/cloud0x9/Schedule-Creator/tree/master/ScheduleCreator/resources/raw

**Comment by jamisonvalentine** [comment]
@wrycode messed up

**Pull request closed without merging**
