### PR TITLE
JavaFX integration and model classes

### PR DESCRIPTION
**Pull request by jamisonvalentine**
- also includes course listing txt files

### CODE REVIEW

**Comment by xsfar** [comment]
looks good to me, everyone else has to agree.

**Comment by ghost** [comment]
Yeah looks great to me. Models are easy to read. Maybe you can show us Tues how you made the javafx files

**Comment by ghost** [comment]
Can you remind me what you used to make the javafx xml files? Edit: it's scenebuilder

Also I just saw that javafx has a webkit thing so we can embed parts of the school's website if we want.

**Comment by jamisonvalentine** [comment]
> Can you remind me what you used to make the javafx xml files? Edit: it's scenebuilder

I used a few different resources and it probably took me more time than it should have to learn.
Mainly these links, and a couple videos to see some of the things in action:
     https://docs.oracle.com/javase/8/javase-clienttechnologies.htm
     https://docs.oracle.com/javase/8/javafx/get-started-tutorial/get_start_apps.htm#JFXST804


> Also I just saw that javafx has a webkit thing so we can embed parts of the school's website if we want.

That's a good idea. I was thinking we could make use of the Course Catalog somewhere in the applicaton.
https://catalog.uncg.edu/courses/

**Comment by ghost** [comment]
Course Scheduler - Wireframe
What do you think of this?

**Comment by ghost** [comment]
@Toldge take a look at this when you get a chance so we can move forward

**Comment by toldge** [comment]
looks good to me!

**Pull request merged**
