### PR TITLE
Refactor; add Admin class with regenDB (including courselists)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
This should be easier to read. 

@cloud0x9 I broke the time and date parsing somehow, can you look at it at some point (no rush)?

**Comment by ghost** [comment]
BTW, this won't run if you still have a user_selected_courses.txt in the raw/ directory. You need to delete that file before running the tests

**Comment by jamisonvalentine** [comment]
Did the time and date parsing ever get fixed?

**Comment by xsfar** [comment]
@jamisonv93 not yet, just started working on it

**Comment by xsfar** [comment]
The UI wont lunch for me, there are some errors in the build xml files, maybe from changed or deleted file names.

**Comment by jamisonvalentine** [comment]
are you working in your branch or this one (nick/refactor)?

**Comment by xsfar** [comment]
@jamisonv93 ideally this branch needs to be merged first so we can work on master, but since I cant get the UI to run for me and your working with UI stuff im not sure, does the UI run for you or do you get errors?

**Comment by jamisonvalentine** [comment]
@cloud0x9 it got pretty messy on my computer so I'm going to start over from master and redo the branch I made today... shouldn't take long to add those changes.

As far as the getting UI the run, I haven't had any problems so far

**Comment by jamisonvalentine** [comment]
@cloud0x9 Do you mean the master branch isn't running?

**Comment by xsfar** [comment]
@jamisonv93 Just the UI on both for me, I can run everything else, but since you can run it then its okay, Its just me, ill figure it out later.
@wrycode Is this okay to merge or are you still working on it?

**Comment by ghost** [comment]
Sorry, fine to merge, I just saw all of this. @cloud0x9 you do have to make sure the DB exists (e.g. by running Tests) before the UI will work, not sure if that was the problem or if it was something else.

**Comment by ghost** [comment]
@cloud0x9 @jamisonv93 Next person to make a pull request: can you uncomment line 93 in Admin.java:
```generateDayTime(inputFilepath, DBPrefix + semester + "/times_and_dates");```
and just include that with one of your commits?

**Pull request merged**
