### PR TITLE
improve schedule grid design

### PR DESCRIPTION
**Pull request by jamisonvalentine**
- Classes that start don't exactly on an hour mark (e.g. 12:30) are displayed correctly on the grid.

### CODE REVIEW

**Comment by jamisonvalentine** [comment]
image

**Comment by jamisonvalentine** [comment]
- Commit also includes improved adjustments of components in the layout when resizing the window

**Comment by jamisonvalentine** [comment]
image

**Comment by jamisonvalentine** [comment]
image

maybe not the best choice of colors, but it's a start

**Comment by jamisonvalentine** [comment]
**Reminder:**
The Add Sections button does not do anything for the time being. The schedule generating method considers all sections for all selected courses. 

I'm holding off until we decide on a better design for choosing or narrowing down sections to consider. 

Also, online sections aren't displayed on the schedule grid, but there will be something to indicate that an online section is chosen (some listView, text below schedule, etc...)

**Comment by xsfar** [comment]
@jamisonv93 looks good and runs

**Pull request merged**
