### PR TITLE
Make most of the UI keyboard-navigable

### PR DESCRIPTION
**Pull request by ghost**
Tab, Shift+Tab, and Enter should work for almost everything now.

### CODE REVIEW

**Comment by ghost** [comment]
Can we change all of the methods and variables to private in
CoursesController and PrimaryController?

**Comment by xsfar** [comment]
@wrycode making everything private or protected caused a bunch of errors.

**Comment by ghost** [comment]
@cloud0x9 I'm working on it, I'll change some of them to private. I'm going through and applying the Style guide right now.

@jamisonv93 do we need the changeToSelectClasses and changeToRegistrationScreen methods in the CoursesController? 

What do you guys think about combining more of the @FXML declarations at the beginning of CoursesController to make it shorter?

**Comment by jamisonvalentine** [comment]
I know I'm late but those methods can actually be deleted. They're in PrimaryController now

**Pull request merged**
