### PR TITLE
Set up for adding entries to the calendar/schedule in the GUI

### PR DESCRIPTION
**Pull request by jamisonvalentine**
implemented new CourseController methods and fixed minor bugs

### CODE REVIEW

**Comment by ghost** [comment]
Seems to work on my end.

Since we are supposed to have an Adapter class, I'm considering moving any calls to the Translator from Semester into the Adapter class. Especially if you're working on this now, because stuff I do in CoursesController won't merge.

**Comment by jamisonvalentine** [comment]
I'm done working on it for at least a few hours so you should safe to work any part you want

**Comment by ghost** [comment]
Also, since you're working on CourseController I'll tell you what I learned while trying to improve the course selection ComboBox:

- it'll be easier to put the list of available courses in a ListView and just use the search box to filter it dynamically. We just need a `filter(String regex, List<String> items)` method and you can connect every change in the search box  to a function call like `availableCourseListView.setItems(filter(searchInput,currentSemester.getCourses()))` (with a special case for a blank search that shows all available courses).

The alternative is to try to jig the ComboBox to do what we want, e.g. one of the many solutions here: https://stackoverflow.com/questions/19924852/autocomplete-combobox-in-javafx

I didn't feel like copy-pasting that much code

**Comment by ghost** [comment]
Oh just saw your response. Ok, I'll work off this branch.

**Comment by jamisonvalentine** [comment]
Work on top of #43:

Prototype for showing added/selected sections on the schedule

**Comment by jamisonvalentine** [comment]
image

**Comment by jamisonvalentine** [comment]
Update: working on algorithm for generating schedules and displaying schedules in GUI

**Comment by jamisonvalentine** [comment]
Still has a number of bugs that need to be resolved but generated schedules are rendered in the GUI now

**Comment by jamisonvalentine** [comment]
image

The Next and Prev buttons do work

**Comment by jamisonvalentine** [comment]
As of now, the algorithm considers every section for all selected courses.

**Comment by xsfar** [comment]
@jamisonv93 is this ready to be merged?(I still cant run anything UI so I don't know if it runs)

**Comment by jamisonvalentine** [comment]
I believe so. Do you know why it's not running for you? Any error messages?

**Comment by xsfar** [comment]
@jamisonv93 

> Error: JavaFX runtime components are missing, and are required to run this application
/....../nbproject/build-impl.xml:1339: The following error occurred while executing this line:
/......./nbproject/build-impl.xml:948: Java returned: 1


Not really sure about the error messages, they are not helpful, I have all the javafx jar files added to the project library and I have javafx scene builder installed, am I missing something ?

**Comment by jamisonvalentine** [comment]
Haven't seen that before. Maybe try deleting src in your project folder and cloning the repo over again?

**Comment by jamisonvalentine** [comment]
Actually, don't merge this yet... More bugs then I thought

**Comment by ghost** [comment]
@cloud0x9 also did you run the Tests at least once before trying to run App.java?

@jamisonv93 what do the previous/next buttons do? Also what about adding a new ListView maybe under the calendar to hold the sections? You could use a remove button analogous to the selected courses ListView, and attach the calendar regeneration method to the remove button and the Add Section button.

**Comment by jamisonvalentine** [comment]
>  what do the previous/next buttons do? Also what about adding a new ListView maybe under the calendar to hold the sections?

Just renders the next permutation of chosen sections... The same as the slider [here](https://digized.github.io/schedule-generator/)

>  Also what about adding a new ListView maybe under the calendar to hold the sections? You could use a remove button analogous to the selected courses ListView, and attach the calendar regeneration method to the remove button and the Add Section button.

Kinda hard to picture what you mean right now but we can see how that idea works too. I'm trying to work out the algorithm right now but once that's done it should be pretty easy to implement Add & Remove sections

**Comment by jamisonvalentine** [comment]
It should be safe to merge now

**Comment by ghost** [comment]
> Just renders the next permutation of chosen sections... The same as the slider here

Oh, ok, I see. 
It's working on my end.

**Pull request merged**
