### PR TITLE
prototyping for new design

### PR DESCRIPTION
**Pull request by jamisonvalentine**
Playing around with an idea...

I don't think it would require that many changes to our existing code.

Let me know what you think....

image

This is the initial view

### CODE REVIEW

**Comment by jamisonvalentine** [comment]
image

**Comment by jamisonvalentine** [comment]
Just prototying for now so whatever you don't see, such as the dark mode toggle button, is going to be added back. This is just the general layout

**Comment by xsfar** [comment]
I like it, I know its still a prototype, but if it could be a slide out menu it would be 
perfect.

**Comment by ghost** [comment]
Looks like a good idea.

**Comment by xsfar** [comment]
@jamisonv93 is this going to me merged or is this fully just a prototype?

**Comment by jamisonvalentine** [comment]
It's not ready to be merged yet so I'll go ahead and close this just in case I don't get to finishing it. I'll more than likely be get to it by Monday so I'll just create another PR then

**Pull request closed without merging**
